### PR TITLE
Document snapshots and Update resources

### PR DESCRIPTION
**Pull request by erikvanoosten**

### CODE REVIEW

**Review by guizmaii — APPROVED** [review]

**Comment by guizmaii** [comment]
You probably need to regenerate the README

**Review by svroonland — APPROVED** [review]

**Comment by erikvanoosten** [comment]
> You probably need to regenerate the README

Isn't that done automatically? Last time I added a page here I didn't do anything else (except waiting for a release).

**Comment by erikvanoosten** [comment]
> You probably need to regenerate the README

I see what you mean now. I will create a new PR.

**Comment by erikvanoosten** [comment]
Done in: https://github.com/zio/zio-kafka/pull/1225

**Pull request merged**
