### PR TITLE
Add listOffsetsAsync to AdminClient

### PR DESCRIPTION
**Pull request by gbecan**
Allows to handle errors (e.g. related to ACL) per topic/partition.
Similar to #486

### CODE REVIEW

**Comment by strokyl** [comment]
@iravid is it possible to know if we have any chance to merge that or you have no interest in it?

**Comment by iravid** [comment]
Hey guys sorry, have not had any time at all for maintenance of this project. @vigoo would you be able to help perhaps?

**Review by vigoo — APPROVED** [review]
Looks good, thanks!

**Comment by vigoo** [comment]
@strokyl can you rebase to latest master please? Then it's good to merge

**Pull request merged**
