### PR TITLE
Try to implement the "one timer per thread"

### PR DESCRIPTION
**Pull request by guizmaii**

### CODE REVIEW

**Review by svroonland — COMMENTED** [review]
Do we have reason to assume ZIO#delay is inefficient?

**Comment by erikvanoosten** [comment]
@guizmaii note that there are 2 more tests as recommended by Adam in #960.

**Comment by guizmaii** [comment]
@erikvanoosten As explained in Discord, this code generates behaviours I can't get my head around. 

The `ref.updateSomeZIO { Some(...) => <code>.as(None) }` is executed twice. I don't understand how that's possible.
Also, when the `p.fail(e)` is called, that doesn't interrupt the Stream while the `p` is correctly completed. Same, I have no idea why 😖

**Comment by erikvanoosten** [comment]
I started with a completely new implementation and also their I do not see any effect of calling p.fail 😞 
Will research further...

**Comment by erikvanoosten** [comment]
@guizmaii With help from Adam I got a working version. See the latest commits in #960.

**Pull request closed without merging**
