### PR TITLE
`fulfillRequests`: prefer using a ZIO while loop over a long chain of `flatMap`

### PR DESCRIPTION
**Pull request by guizmaii**

### CODE REVIEW

**Comment by erikvanoosten** [comment]
@guizmaii I though this was interesting. Why did you close it again? Was the performance not good?

**Comment by guizmaii** [comment]
@erikvanoosten I closed it because Adam told me that it would probably not change anything, see https://discord.com/channels/629491597070827530/630498701860929559/1085913117965431004, and because I wasn't seeing anything in the benchmarks anyway

**Comment by erikvanoosten** [comment]
I see. Well, if there is no down side, I found the way you structured the code in this PR more readable than what was there before. It took me some time before I realized that there was a `var` being mutated...

**Comment by adamgfraser** [comment]
Yes may still make code easier to read and reason about!

**Comment by guizmaii** [comment]
Ok, let me reopen this PR then
Thanks for the feedback  :)

**Comment by guizmaii** [comment]
See https://github.com/zio/zio-kafka/pull/728

**Pull request closed without merging**
