### PR TITLE
Add tests for Pattern based Subsctiption

### PR DESCRIPTION
**Pull request by pinikeizman**
Hey, I had some trouble configuring a Subscription with Regex. 
I added this test to make sure it works.
I might be missing something would love to get some help here.

This is what I got so far:
- Metadata refresh is on 1s for the apache Kafka consumer.
- I added some logs in the rebalance listener CB and they didn't invoke (which they did invoke when I used Topic set subscription)

### CODE REVIEW

**Comment by iravid** [comment]
Thanks for adding the test @pinikeizman! It's currently failing on some compile errors. Let me know if you need help in fixing them.

**Comment by iravid** [comment]
@pinikeizman From what I recall, pattern subscriptions don't work with start/end anchors (`^`, `$`). Can you try something like `topic[0-9]+` for the pattern?

**Comment by pinikeizman** [comment]
@iravid  NP I'll try it.

**Comment by pinikeizman** [comment]
@iravid it still fails.

**Comment by iravid** [comment]
Hmm that's pretty strange. There's no particular difference between pattern subscriptions and topic subscriptions in this library's code.

Thanks for the test, I'll have time to look into this next week. 

Feel free to keep poking around yourself - it may be beneficial to increase the logging level when running the tests and see what's the output from the consumer and the embedded Kafka broker.

**Comment by iravid** [comment]
Cherry-picked into #53

**Pull request closed without merging**
