### PR TITLE
External offset retrieval

### PR DESCRIPTION
**Pull request by svroonland**
Support retrieving offsets from an external source by providing an `OffsetRetrieval.Manual(getOffsets)` to `ConsumerSettings`.

Implements #102

### CODE REVIEW

**Comment by svroonland** [comment]
@iravid or @adamgfraser if you have time to review this one?

**Comment by iravid** [comment]
@svroonland Thanks for the reminder. I'll review today.

**Comment by svroonland** [comment]
Good point. Well, there's no reason why clients could not call `seek*` during streaming to change the offset. Although it's not very well determined what the next processed message would be after calling seek. The same can be said for calling `subscribe` and `unsubscribe`. 

I guess the question boils down to: do we want to support that and can we do that in a way that is useful (deterministic) to the users. What do you think?

**Comment by iravid** [comment]
Let's deprecate them in a follow-up. I don't see a way to deterministically use them currently.

**Pull request merged**
