### PR TITLE
Introduce zio kafka test

### PR DESCRIPTION
**Pull request by tewecske**
What do you think about this? I think these test utils are useful for anyone using zio-kafka so how about publishing them? This is a preview and I'm open to any suggestions especially as I'm not an sbt or zio expert at all :)

### CODE REVIEW

**Comment by tewecske** [comment]
@iravid
I actually forgot to check the issues before I started this but this is basically the base for https://github.com/zio/zio-kafka/issues/61 and https://github.com/zio/zio-kafka/issues/155
When I made a sample app for zio-kafka I was wishing for something like this :)
This is a draft so I'll check what else can be done here and also open for any suggestions.

**Comment by LeonardMeyer** [comment]
This is something we'd need as well. Long story short we used Testcontainers at work for integration testing but ran into some weird issues with it. I thought it would've been nice if zio-kafka provided stubs for `Producer` and `Consumer` using the same in memory queue (ZIO has one). We started doing it for `Producer` and it looked easy enough but `Consumer` seems a bit trickier with the multiple method and polling mechanism. 

But this PR looks even better and more general, what is the hold up to merge this besides the conflicts ?

**Comment by tewecske** [comment]
@LeonardMeyer I just didn't get any response if this is good or not. I can clean this up and if necessary add more stuff to it.

**Comment by LeonardMeyer** [comment]
@iravid Could we move this forward ? This is a nice addition to the lib IMO.

@tewecske I saw a few things in the PR that should be changed but maybe because it hasn't been rebased ? The most important one are the produce methods in `KafkaTestUtils` that should somewhat mirror those in [Producer](https://github.com/zio/zio-kafka/blob/master/src/main/scala/zio/kafka/producer/Producer.scala) by being generic and taking serializers directly.

**Comment by tewecske** [comment]
@LeonardMeyer I don't want to change any code in this PR if not necessary to keep it simple. This is only an extraction of test utils into a separate module.
I will clean this up and resolve conflicts and ask for a merge.
If you have ideas for additional work then create a new ticket please. I can work on that after this one is done.

**Comment by vigoo** [comment]
@tewecske can you make this up to date? I merged a couple of open PRs so there are conflicts

**Comment by tewecske** [comment]
@vigoo Updated.

**Review by vigoo — APPROVED** [review]

**Review by vigoo — APPROVED** [review]

**Comment by tewecske** [comment]
@vigoo Thanks for the merge! :)

@LeonardMeyer If you want more stuff in test utils open a new ticket please.

**Pull request merged**
