### PR TITLE
Remove unnecessary nowarn

### PR DESCRIPTION
**Pull request by erikvanoosten**
Intellij complains about the nowarn annotation. As it is indeed not really necessary, this PR removes it.

### CODE REVIEW

**Comment by svroonland** [comment]
Is unfortunately failing on 2.12, the version the nowarn is for..

**Comment by erikvanoosten** [comment]
> Is unfortunately failing on 2.12, the version the nowarn is for..

Ah, understood!

**Comment by erikvanoosten** [comment]
> Is unfortunately failing on 2.12, the version the nowarn is for..

@svroonland  I found a different way to suppress the warning that also works for 2.12 😄

**Review by svroonland — APPROVED** [review]
Esoteric, but nice :)

**Pull request merged**
