### PR TITLE
Producer alternative send chunk

### PR DESCRIPTION
**Pull request by domdorn**
for discussion: alternative implementation of the sendChunk method..

### CODE REVIEW

**Comment by erikvanoosten** [comment]
Nice idea! This will work definitely better then the proposal in #1283. Is it okay if I take this and work it out further?

**Comment by domdorn** [comment]
Yes, i'd highly appreciate that!!

Dominik Dorn
https://dominikdorn.com/ | https://twitter.com/domdorn
XING: https://www.xing.com/profile/Dominik_Dorn
LINKEDIN: https://www.linkedin.com/in/dominik-dorn/

**Comment by erikvanoosten** [comment]
Sorry, this won't work either. We cannot afford to wait for the broker to acknowledge every record, it would be super slow!

**Comment by erikvanoosten** [comment]
> Sorry, this won't work either. We cannot afford to wait for the broker to acknowledge every record, it would be super slow!

Oops, again sorry. That comment doesn't apply to your code but a refactoring I did 😊.
There are still 2 other problems with this proposal though:
- it uses zio.fromJavaFuture which creates 1 thread per record, the thread is blocked until the record is acknowledged
- the records are no longer send in order

**Comment by domdorn** [comment]
closed in favour of #1286 (although I liked my ZIO.async stuff..)

**Pull request closed without merging**
