### PR TITLE
Execute KafkaProducer#send calls directly and not on the blocking thread pool

### PR DESCRIPTION
**Pull request by svroonland**
See #531

### CODE REVIEW

**Comment by iravid** [comment]
I think this is generally fine but just want to say that in catastrophic cases where the broker is down (for example) and the producer buffer fills up, calls to `send` most definitely will block. I think this is documented in the Java API.

**Review by iravid — APPROVED** [review]

**Comment by svroonland** [comment]
Right, found it:
```
When the buffer space is exhausted additional send calls will block. The threshold for time to block is determined by <code>max.block.ms</code> after which it throws a TimeoutException.
```

Thanks!

**Comment by guizmaii** [comment]
Can't we bypass this mechanism from the Java client by implementing our own buffer and using a non-blocking "blocking mechanism"? Might be a crazy idea 🤔😅

**Comment by svroonland** [comment]
I suppose we could yes, but it's quite some effort for an exceptional case. Feel free to do so of course! :)

**Pull request merged**
