### PR TITLE
add test case for the runloop polling behavior

### PR DESCRIPTION
**Pull request by tnielens**
Relates to #664. Add test case demonstrating the expected behavior.

### CODE REVIEW

**Comment by svroonland** [comment]
@tnielens with #683 merged, what shall we do with this PR?

**Comment by tnielens** [comment]
The test verifies that messages are streamed without delay in a certain poll timeout condition. 
I'll have a look at your pr to see if similar test cases were added. If not, I can finish it.

**Comment by tnielens** [comment]
@svroonland I updated the branch. There are now two test cases. They test the requirements of #664 and currently fail. Could you have a look? I think these cases should pass if #664 is considered implemented.

**Comment by svroonland** [comment]
@tnielens I checked it last night locally, if you update your branch with master, you should find that the tests succeed.

**Comment by tnielens** [comment]
I've adapted the tests to the latest master commit. Feel free to close this PR if the test cases are redundant or provide no value to the project.

**Comment by svroonland** [comment]
> Ah it seems the pollInterval field was removed from the ConsumerSettings. Was that part of release 2.1?
Part of one of the latest merged PRs (#736), not released yet.

**Comment by svroonland** [comment]
We can keep the second test. The first one doesn't really test that it polls immediately, because it doesn't mean there will immediately be any records available in the stream.

**Review by svroonland — APPROVED** [review]

**Pull request merged**
