### PR TITLE
Benchmark history cleanup

### PR DESCRIPTION
**Pull request by erikvanoosten**
This PR contains a number of commits that each clean up a part of the benchmark history:

* Remove data for `JMHSample_01_HelloWorld.wellHelloThere` benchmark
* Remove data for `ZioKafkaNoOptimisticResumeBenchmarks` benchmark (plus one more `JMHSample_01_HelloWorld.wellHelloThere`)
* Remove data for `ZioKafkaNoPrefetchingBenchmarks`
* Remove data for `New commit interface` branch to get rid of the high peak in the graphs
* Benchmarks `zio.kafka.bench.ConsumersComparisonBenchmark.*` were moved to another package. By renaming the old data, these data points are joined again in the same graphs.
* Remove PR commits older than a month

The last step was done with a bash script and can be repeated regularly. Documentation for that will follow in a later PR.

### CODE REVIEW

**Comment by svroonland** [comment]
Do the benchmarks still run on PR branches or did we remove that and it runs just on master?

**Comment by erikvanoosten** [comment]
> Do the benchmarks still run on PR branches or did we remove that and it runs just on master?

This PR only removes the (old) results of PR benchmarks. For the rest I did not change anything. So when benchmarks are running is still the same.

**Comment by erikvanoosten** [comment]
BTW, this is a low risk change. If it doesn't work, we can simply revert and all the data is back! 🙂

**Comment by erikvanoosten** [comment]
I merged because:
* it is a low risk change, it can be reverted at any time without affecting releases
* I don't want to keep rebasing it

Before:
Screenshot 2023-10-11 at 08-24-50 Benchmarks

After:
Screenshot 2023-10-11 at 08-36-42 Benchmarks

**Comment by erikvanoosten** [comment]
One more correction in https://github.com/zio/zio-kafka/commit/24e7382d55f63442240e1129d5e0fefcc69cdc4e we get:

Screenshot 2023-10-11 at 09-37-42 Benchmarks

**Pull request merged**
