### PR TITLE
Drop support for scala 2.12

### PR DESCRIPTION
**Pull request by erikvanoosten**
Also: remove unused variables in build.sbt.

### CODE REVIEW

**Comment by svroonland** [comment]
There's a 2.12 mention in https://github.com/zio/zio-kafka/blob/master/.mergify.yml

**Comment by svroonland** [comment]
Sorry, wrong button

**Comment by erikvanoosten** [comment]
> There's a 2.12 mention in https://github.com/zio/zio-kafka/blob/master/.mergify.yml

Fixed in https://github.com/zio/zio-kafka/pull/1104/commits/ce17c2bf6c403b2fd06d16adb5f5b7d17830b84f.

I do not see what this file does. Should we add scala 3?

**Review by svroonland — APPROVED** [review]

**Comment by svroonland** [comment]
@guizmaii Do you know if we're still using mergify?

**Comment by erikvanoosten** [comment]
> @guizmaii Do you know if we're still using mergify?

Recent pull requests from scala steward have all been merged by us, well mostly by @guizmaii 🙂

**Comment by guizmaii** [comment]
> Do you know if we're still using mergify?

I think we're not using it anymore

**Pull request merged**
