### PR TITLE
Remove `Consumer::stopConsumption`

### PR DESCRIPTION
**Pull request by guizmaii**

### CODE REVIEW

**Comment by erikvanoosten** [comment]
There is one problem with this approach. When we interrupt the stream, pending commit may not be completed. When we call stopConsumption, the stream can continue to work on whatever it got and complete without errors.

**Comment by guizmaii** [comment]
@erikvanoosten As explained in Discord, I think it's a user issue, not a zio-kafka issue. See https://discord.com/channels/629491597070827530/629497941719121960/1120624484035067934

**Comment by erikvanoosten** [comment]
> @erikvanoosten As explained in Discord, I think it's a user issue, not a zio-kafka issue. See https://discord.com/channels/629491597070827530/629497941719121960/1120624484035067934

I see that yet. I'll read it!

**Comment by svroonland** [comment]
If we have a satisfying way to do this in user space and add that to the docs, I'm all for removing this method and the extra complexity it brings. Did you test it already?

**Comment by guizmaii** [comment]
> Did you test it already?
 
 I just started the PR this morning to see what it'd give and what would break.
 It needs more work I'll not have time to do this week, focusing on my project.
 If you wanna take the subject, go for it :)
 
 Have a look at the discussion I had with a user in Discord. It might be interesting to provide an "interuptor" to the user so that it's easy for them to stop a Stream
 
 For us, it'd probably just be a Promise wrapped in an nice, easy-to-user interface

**Comment by guizmaii** [comment]
Closed in favour of https://github.com/zio/zio-kafka/issues/941

**Pull request closed without merging**
