### PR TITLE
Fix `Consumer.fromJavaConsumer` and `Producer.fromJavaProducer` type signatures

### PR DESCRIPTION
**Pull request by devsprint**
Found the issue while trying to wrap the kafka Consumer and Producer with KafkaTelemetry to integrat Open Telemetry for tracing.

Added a pair of convenient methods.

### CODE REVIEW

**Comment by guizmaii** [comment]
@devsprint What's the diff with the functions just above yours? 🤔

**Comment by devsprint** [comment]
Just rely on the interface instead of implementation

**Comment by devsprint** [comment]
Not sure that is the best approach. maybe we can have a single method that use the interface as parameter instead of the implementation.

**Comment by guizmaii** [comment]
> Just rely on the interface instead of implementation

Can you instead fix the previous functions? It's not good to rely on the implementation. The interfaces should have been used

**Comment by devsprint** [comment]
yes. I will update the branch in few minutes.

**Comment by guizmaii** [comment]
(BTW, I'm fixing the CI here: https://github.com/zio/zio-kafka/pull/1032. I'll merge my PR as soon as the CI passes)

**Review by svroonland — APPROVED** [review]

**Review by guizmaii — APPROVED** [review]

**Comment by guizmaii** [comment]
@devsprint I fixed the CI in the `master` branch (sorry about that). Can you rebase your branch, please?

**Pull request merged**
