### PR TITLE
Clean/update project config

### PR DESCRIPTION
**Pull request by guizmaii**
- Update Scala version
- Uniformize libraries versions
- Add dependabot config to help us maintain the Gitub Actions
- Update scalafmt && format code

### CODE REVIEW

**Comment by svroonland** [comment]
@guizmaii Could you update the branch with master? 

I'm not sure about introducing dependabot, I'd prefer it to be consistent with the rest of the ZIO projects. @mijicd @vigoo @adamgfraser what's your opinion on this?

**Comment by adamgfraser** [comment]
@svroonland We've used it on a couple of other ZIO projects. I haven't had a hugely positive impression (just a lot of noise for low priority updates that would be better done as a batch on some interval) but I don't have a strong opinion so feel free to do whatever you want.

**Comment by mijicd** [comment]
I'm with Adam here. It works, but you'll need to assess if it fits your workflow as it's going to be "loud".

**Comment by svroonland** [comment]
Isn't it kind of redundant with scala-steward?

**Comment by guizmaii** [comment]
> Isn't it kind of redundant with scala-steward?

No it's not. Dependabot here update your Github Actions (all the `use: setup/java@xxx`, not your Scala project

**Comment by guizmaii** [comment]
> Could you update the branch with master?

Done :)

**Review by svroonland — APPROVED** [review]

**Comment by svroonland** [comment]
Thanks!

**Pull request merged**
