### PR TITLE
Publish Docs to NPM Registry

### PR DESCRIPTION
**Pull request by khajavi**

### CODE REVIEW

**Comment by khajavi** [comment]
This is ready for review.

**Comment by khajavi** [comment]
This is ready for review.

**Review by jdegoes — APPROVED** [review]

**Comment by jdegoes** [comment]
@khajavi Some tasks not progressing. Can you look into?

**Comment by svroonland** [comment]
Looks like the branch protection rules' status check names have changed. I'll see if I can fix that.

**Pull request merged**
